version: '3'

services:
  song-service:
    image: 'song-service:latest'
    container_name: 'song-service-container'
    build:
      context: song-service
    ports:
      - '8080:8080'
    depends_on:
      - song-db
    env_file:
      - song-service/.env

  song-db:
    image: 'postgres:13'
    container_name: song-db
    ports:
      - '5432:5432'
    env_file:
      - song-service/.env
    volumes:
      - ./song-service/song-init.sql:/docker-entrypoint-initdb.d/song-init.sql

  resource-service:
    image: 'resource-service:latest'
    container_name: 'resource-service-container'
    build:
      context: resource-service
    ports:
      - '8081:8080'
    depends_on:
      - resource-db
      - song-service
    env_file:
      - resource-service/.env

  resource-db:
    image: 'postgres:13'
    container_name: resource-db
    ports:
      - '5433:5432'
    env_file:
      - resource-service/.env
    volumes:
      - ./resource-service/resource-init.sql:/docker-entrypoint-initdb.d/resource-init.sql