apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: k8s-program
data:
  POSTGRES_DB_RESOURCE: "resource"
  POSTGRES_DB_SONG: "song"

  SERVER_PORT_RESOURCE: "8081"
  SPRING_DATASOURCE_URL_RESOURCE: "jdbc:postgresql://resource-db:5433/resource"
  SONG_SERVICE_URL_RESOURCE: "http://song-service:8080/songs"

  SERVER_PORT_SONG: "8080"
  SPRING_DATASOURCE_URL_SONG: "jdbc:postgresql://song-db:5432/song"

  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_DATASOURCE_PASSWORD: "password"

  INIT_SQL_SONG: |
    CREATE TABLE IF NOT EXISTS resource
    (
        id   serial not null primary key,
        data bytea
    );

  INIT_SQL_RESOURCE: |
    CREATE TABLE IF NOT EXISTS song
    (
        id          serial not null primary key,
        name        varchar,
        artist      varchar,
        album       varchar,
        duration    varchar,
        resource_id INT    not null,
        year        varchar
    );
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: k8s-program
data:
  POSTGRES_USER: "dXNlcg=="
  POSTGRES_PASSWORD: "cGFzc3dvcmQ="


