apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-service-deployment
  namespace: k8s-program
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-service
  template:
    metadata:
      namespace: k8s-program
      labels:
        app: resource-service
    spec:
      containers:
        - name: resource-service
          image: resource-service
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health/liveness
            initialDelaySeconds: 100
            periodSeconds: 10
            failureThreshold: 2
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health/readiness
            initialDelaySeconds: 100
            periodSeconds: 10
            failureThreshold: 2
            timeoutSeconds: 5
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SERVER_PORT_RESOURCE
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL_RESOURCE
            - name: SONG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SONG_SERVICE_URL_RESOURCE
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8081
