apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resource-db
  namespace: k8s-program
spec:
  serviceName: "resource-db"
  selector:
    matchLabels:
      app: resource-db
  template:
    metadata:
      namespace: k8s-program
      labels:
        app: resource-db
    spec:
      containers:
        - name: resource-db
          image: resource-db
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5433
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: resource
          volumeMounts:
            - name: resource-db-pvc
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: resource-db-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi