apiVersion: v1
kind: Service
metadata:
  name: resource-service-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: resource-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
