apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service-deployment
  namespace: k8s-program
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-service
  template:
    metadata:
      namespace: k8s-program
      labels:
        app: song-service
    spec:
      containers:
        - name: song-service
          image: song-service
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 100
            periodSeconds: 10
            failureThreshold: 2
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 100
            periodSeconds: 10
            failureThreshold: 2
            timeoutSeconds: 5
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SERVER_PORT_SONG
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL_SONG
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8080
