apiVersion: v1
kind: Service
metadata:
  name: resource-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: resource-db
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432
  type: ClusterIP