apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resource-db
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "resource-db"
  selector:
    matchLabels:
      app: resource-db
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: resource-db
    spec:
      containers:
        - name: resource-db
          image: postgres:16
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          ports:
            - containerPort: 5433
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB_RESOURCE
          volumeMounts:
            - name: resource-db-pvc
              mountPath: /var/lib/postgresql/data
            - name: resource-db-init-vol
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: INIT_SQL_RESOURCE
      volumes:
        - name: resource-db-init-vol
          configMap:
            name: app-config
  volumeClaimTemplates:
    - metadata:
        name: resource-db-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi