apiVersion: v1
kind: Service
metadata:
  name: song-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: song-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
