apiVersion: v1
kind: Service
metadata:
  name: song-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: song-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP